### ISSUE TITLE
[BUG] [Ruby Client]getStrings should return same format for both translation bundles and sources

### ISSUE THREAD

**Issue by Xiaochao8** [vmware/singleton#1351] opened 2021-11-01 02:47 UTC
When translations are available, getStrings returns as below:
{
	"locale": "en",
	"component": "component-1",
	"messages": {...}
}

When translations aren't avaulable, and sources are available, getStrings returns as below:
{
	"source": {...}
}

The format should be consistent between translations and sources.

**Comment by linr211** [comment] 2021-11-01 12:21
fixed it on v0.1.7

**Comment by lyiyu66** [comment] 2021-11-15 10:47
The issue is fixed with commit 4c2a80e7fdc91c8c36dcadb05ca54565523766bf.
![image](https://user-images.githubusercontent.com/51813046/141768584-4c8e5bc4-8eb3-40c6-8e45-705243761d13.png)

**Comment by lyiyu66** [comment] 2021-11-15 10:48
Closing it according to above comment.

**Closed by lyiyu66** 2021-11-15 10:48 UTC
Labels: kind/bug, priority/high, area/ruby-client
