### ISSUE TITLE
[BUG] [Go Service]currencies response data is as CN region when requesting "currencies" pattern for language(zh-Hans-CN) and invalid region(US) with pattern API.

### ISSUE THREAD

**Issue by JiLiang888** [vmware/singleton#2356] opened 2023-05-31 02:14 UTC
**Describe the bug**
[BUG] [Go Service]currencies response data is as CN region when requesting "currencies" pattern for language(zh-Hans-CN) and invalid region(US) with pattern API.

**To Reproduce**
1. Go to 'i18n/api/v2/formatting/patterns'
2. Input "zh-Hans-CN" as language, "US" as region and "currencies" as pattern.
3. See the response:
<img width="1433" alt="image" src="https://github.com/vmware/singleton/assets/82644009/194440ab-c78c-4bc5-86b9-e68eb3062dd2">

**Expected behavior**
currencies response data should be as US region

commit fb3c0bb0db9b2cac59097d3250c10e4cbf180998

**Comment by Xiaochao8** [comment] 2023-05-31 03:01
The specifications have been changed.
`Currencies` will follow `language` part.

**Comment by lyiyu66** [comment] 2023-11-01 06:56
The issue is fixed with commit: 520bc957796d4ce47eb94f5e820408332572e1dd
![image](https://github.com/vmware/singleton/assets/51813046/e2f82690-e8bc-4550-9316-e609db407bd5)

**Closed by lyiyu66** 2023-11-01 06:56 UTC
Labels: priority/medium, area/go-service
