### ISSUE TITLE
[BUG] [JS client] Command 'load-locale-data' cannot work

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#1205] opened 2021-07-14 01:33 UTC
**Describe the bug**
In Singleton JS lib, here provides 2 clis, one (collect-source-bundle) is to post source to Singleton Service, the other (load-locale-data) is to fetch translation and formatting data from Singleton Service to local; but now, the second one (load-locale-data) doesn't work.

**To Reproduce**
1. Integrate Singleton JS lib into product code
2. Setup the CLI into package.json
3. `npm run load-locale-data` 
Error messages:
```
(node:97390) UnhandledPromiseRejectionWarning: TypeError: that.vipService.loadCombineData is not a function
    at .../node_modules/@singleton-i18n/js-core-sdk/cli/load-locale-data.js:75:43
    at new Promise (<anonymous>)
    at LoadLocaleData.generateLocaleDataBundles (.../node_modules/@singleton-i18n/js-core-sdk/cli/load-locale-data.js:69:23)
    at run (.../node_modules/@singleton-i18n/js-core-sdk/cli/load-locale-data.js:185:22)
    at Object.<anonymous> (.../node_modules/@singleton-i18n/js-core-sdk/cli/load-locale-data.js:201:1)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
(Use node --trace-warnings ... to show where the warning was created)
(node:97390) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:97390) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
=
```

**Expected behavior**
The CLI runs successfully, and  the files that including specific translaiton and formatting data will be generated into the specific folder.

**Comment by lyiyu66** [comment] 2021-07-30 03:31
The issue is fixed with commit 3284352bd562d50618b7693658c5e6a28c24c600.

**Closed by lyiyu66** 2021-07-30 03:31 UTC
Labels: area/js-client, kind/bug, priority/high
