### ISSUE TITLE
[BUG] [Java Service]Response data should remove duplicate data if request dup components in get peoducts translation api

### ISSUE THREAD

**Issue by JiLiang888** [vmware/singleton#2701] opened 2023-09-25 06:36 UTC
**Describe the bug**
[BUG] [Java Service]Response data should remove duplicate data if request dup components in get peoducts translation api

**To Reproduce**
1. Go to 'GET[/i18n/api/v2/translation/products/{productName}/versions/{version}'
2. Request parameters as
<img width="1201" alt="image" src="https://github.com/vmware/singleton/assets/82644009/39114513-1dd5-4004-8d75-0a86f6e7ef93">

3. See response
response code =200 ;
<img width="1168" alt="image" src="https://github.com/vmware/singleton/assets/82644009/ea885a75-2b0f-4615-8f7a-ca019a0639a1">

**Expected behavior**
response data should remove duplicate data

build.number.buildnumber=30dcfe321eeac05e989e9375563ba76465b4b62f

**Comment by lyiyu66** [comment] 2023-10-19 02:59
The issue is fixed with commit:a8e8cb5eb1d65a2d238edce3e433620b73ce8673
![image](https://github.com/vmware/singleton/assets/51813046/610c05c5-644e-4693-a849-ef5779b7c34a)

**Closed by lyiyu66** 2023-10-19 02:59 UTC
Labels: area/java-service, priority/medium
