### ISSUE TITLE
[BUG] G11n-java-client New workflow's Translation.getMessage must be able to use latest source messages from VIP service

### ISSUE THREAD

**Issue by jessiejuachon** [vmware/singleton#812] opened 2020-10-02 21:07 UTC
**Describe the bug**
TranslationMessage.getMessage is not able to fetch "latest" messages from VIP service and use them as source messages. This must be done as fallback for when messages_source.json is not supported locally.

**To Reproduce**
1. Do not configure offline bubndle in config.properties
2. In VIP service, add new source strings to "latest", but not to "en" locale (a.k.a out-or-synch scenario)
3. In the client, call TranslationMessage.getMessage("en", component, key);
3. A VIP exception is thrown.

**Expected behavior**
Message that was added to "latest" in VIP service must be returned.

**Additional context**
This is to support use cases where source bundles are not together with the client code but instead are residing in other microservice's source code.

**Comment by lyiyu66** [comment] 2020-10-20 08:42
The issue is fixed with commit bfb7deb14393b24c26d37301d5a18b44ab1b1b23.

**Closed by lyiyu66** 2020-10-20 08:42 UTC
Labels: kind/bug, priority/high
