### ISSUE TITLE
[BUG] [Go Service]Response data should remove duplicate data if request dup version in get multiVersion translation api #

### ISSUE THREAD

**Issue by JiLiang888** [vmware/singleton#2765] opened 2023-10-17 02:39 UTC
**Describe the bug**
[BUG] [Go Service]Response data should remove duplicate data if request dup version in get multiVersion translation api #

**To Reproduce**
1. Go to '[/translation/products/{productName}/multiVersionKey]'
2. Request parameters as
<img width="1209" alt="image" src="https://github.com/vmware/singleton/assets/82644009/4704389d-b94d-459b-8eb1-4c1d2bb88c53">
3.See response
response code =200 ;
<img width="1159" alt="image" src="https://github.com/vmware/singleton/assets/82644009/97e00533-81ae-43f7-884a-1a3d4607e168">

**Expected behavior**
1.response code = 200;
2.response data should remove duplicate data

commit d68ff43c33fcff647c2c87ffdada85a7a17c5b70

**Comment by lyiyu66** [comment] 2023-11-27 10:13
The issue is fixed with commit b61ecc2a01e54a50f92c30ff93a5e2edd33942d9:
![image](https://github.com/vmware/singleton/assets/51813046/78b74b1e-e65a-46ca-8497-5a087879522b)

**Closed by lyiyu66** 2023-11-27 10:13 UTC
Labels: kind/bug, priority/low, area/go-service
