### ISSUE TITLE
[BUG] [JAVA Client] some i18n API URL fails with java.lang.NullPointerException

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#2255] opened 2023-04-11 06:41 UTC
request -- xxx/i18n/component
response -- 
java.lang.NullPointerException
 com.vmware.vipclient.i18n.filters.VIPComponentFilter.getParamFromQuery(VIPComponentFilter.java:78)
 com.vmware.vipclient.i18n.filters.VIPComponentFilter.doFilter(VIPComponentFilter.java:36)
 org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
 com.vmware.loginsight.web.utilities.UTF8EncodingFilter.doFilter(UTF8EncodingFilter.java:24)
 com.vmware.loginsight.web.utilities.CacheControlFilter.doFilter(CacheControlFilter.java:30)

request -- xxx/i18n/pattern
response -- 
java.lang.NullPointerException
 com.vmware.vipclient.i18n.filters.VIPPatternFilter.getParamFromQuery(VIPPatternFilter.java:53)
 com.vmware.vipclient.i18n.filters.VIPPatternFilter.doFilter(VIPPatternFilter.java:35)
 org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
 com.vmware.loginsight.web.utilities.UTF8EncodingFilter.doFilter(UTF8EncodingFilter.java:24)
 com.vmware.loginsight.web.utilities.CacheControlFilter.doFilter(CacheControlFilter.java:30)

request -- xxx/i18n/component?sdf=34
response --
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
 java.lang.String.substring(String.java:1967)
 com.vmware.vipclient.i18n.filters.VIPComponentFilter.getParamFromURI(VIPComponentFilter.java:68)
 com.vmware.vipclient.i18n.filters.VIPComponentFilter.doFilter(VIPComponentFilter.java:37)
 org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
 com.vmware.loginsight.web.utilities.UTF8EncodingFilter.doFilter(UTF8EncodingFilter.java:24)
 com.vmware.loginsight.web.utilities.CacheControlFilter.doFilter(CacheControlFilter.java:30)

**Comment by lyiyu66** [comment] 2023-07-24 09:25
The issue is fixed with commit 5ab078f950b2431fa5ad5bb367258317203b0953
![image](https://github.com/vmware/singleton/assets/51813046/f559fa4d-3adc-49c3-b470-51a7d6fe9b9f)
![image](https://github.com/vmware/singleton/assets/51813046/b8ab6c06-f4a6-4cc2-b600-8f64e93918bd)
![image](https://github.com/vmware/singleton/assets/51813046/2982c0b2-2105-49c5-84d3-faf39440aba8)

**Closed by lyiyu66** 2023-07-24 09:25 UTC
Labels: kind/bug, area/java-client, priority/high
