### ISSUE TITLE
[BUG] [Ruby Client] Cache refresh of source bundle is incorrect

### ISSUE THREAD

**Issue by jessiejuachon** [vmware/singleton#1574] opened 2022-03-08 17:11 UTC
**Describe the bug**
After the client cache has expired, cached source bundle is incorrect.

**To Reproduce**
1. Use the client library in a sample application, set the cache expiry to the minimum, and start the application.
2. When application starts, data in cache is something like this:
```
{"default"=>
  {"account.status.aws.api.issues.access_denied"=>"AWS API access was denied.",
   "account.status.aws.api.issues.aws_unreachable"=>"The AWS API was not responding properly.",
```
3. After expiration, data in cache is overwritten by "old"/"remote" source bundle:
```
{"productName"=>"test",
 "version"=>"4.8.1",
 "locale"=>"en",
 "component"=>"i18n",
 "messages"=>
  {"account.status.aws.api.issues.access_denied"=>"\#@AWS API access was denied.@#",
   "account.status.aws.api.issues.aws_unreachable"=>"\#@The AWS API was not responding properly.@#",

```

**Expected behavior**
Cache of local source bundle will not be overwritten.

**Comment by lyiyu66** [comment] 2022-03-09 10:15
The issue is fixed with commit 020a934f7668d002962cd269b7cffed621b42d9d.
After cache is expired, it will be read from source bundle again.
Scenario 1: source is not updated after cache is expired.
@Result: s_Hello world
@Result: s_Hello world

Scenario 2: source has been updated after cache is expired.
@Result: s_Hello world
@Result: s_Hello world11

**Closed** 2022-03-10 01:19 UTC
Labels: kind/bug, priority/high, area/ruby-client
