### ISSUE TITLE
[BUG] [ruby client] Duplicated http requests happen in string-based API if the component is not existing

### ISSUE THREAD

**Issue by linr211** [vmware/singleton#1445] opened 2022-01-18 04:10 UTC
**Describe the bug**
Duplicated http requests happen in string-based API if the component is not existing.

**To Reproduce**
1. Go to 'sgtncllient.log' and check the logs

**Expected behavior**
only one http request happen for non-existing component on service

**Screenshots**
If applicable, add screenshots to help you explain your issue

**Desktop (please complete the following information):**
 - Browser Name [e.g. chrome, safari]
 - Browser Version [e.g. 22]

**Additional context**

**Comment by lyiyu66** [comment] 2022-01-18 11:41
The issue is fixed with build https://rubygems.org/gems/singleton-client-test/versions/0.7.0.25.
Cache will be persisted 1 hour for below online scenarios:
1. Request a key with the component isn't in Singleton service.
2. Request a key with the locale doesn't exist in Singleton service.

**Closed** 2022-01-20 02:24 UTC
Labels: kind/bug
