### ISSUE TITLE
[BUG][Go Service]should response 400 when request only one parameters in about-version-api

### ISSUE THREAD

**Issue by JiLiang888** [vmware/singleton#2615] opened 2023-08-29 08:15 UTC
**Describe the bug**
[BUG][Go Service]should response 400 when request only one parameter in about-version-api

**To Reproduce**
1. Go to 'about-version-api'
2. request only one parameters,such as product name= VMwareVIP2018, or version=1.0
3. see response is 200
<img width="881" alt="image" src="https://github.com/vmware/singleton/assets/82644009/b2ff3350-c835-4830-a273-292ed3294978">

**Expected behavior**
/response/code=400;/response/message=Only one parameter of 'productName' and 'version' is provided, they should be used in pairs!;

https://github.com/vmware/singleton/commit/6cd6319be3792b0702a5cf9d4370d4294b683881

**Comment by lyiyu66** [comment] 2023-11-27 08:27
The issue is fixed with commit b61ecc2a01e54a50f92c30ff93a5e2edd33942d9:
![image](https://github.com/vmware/singleton/assets/51813046/ff3a60c7-d3b5-4de5-a410-8f09bd677fb8)

The minor typo issue will be tracked with another issue.

**Closed by lyiyu66** 2023-11-27 08:27 UTC
Labels: priority/medium
