### ISSUE TITLE
[BUG][Go Service] level2 data should follow the valid combined locale rather than language

### ISSUE THREAD

**Issue by Xiaochao8** [vmware/singleton#2641] opened 2023-09-07 03:03 UTC
When getting level 2 data with language and region, and the combined locale is valid. The returned data should follow the combined locale rather than language.

**Comment by lyiyu66** [comment] 2023-11-01 08:55
The issue is fixed with commit 520bc957796d4ce47eb94f5e820408332572e1dd
One minor issue is about when language/region is zh-hans/tw, the localeID is empty, it is tracked with issue https://github.com/vmware/singleton/issues/2796

**Closed by lyiyu66** 2023-11-01 08:55 UTC
Labels: kind/bug, priority/medium, area/go-service
