### ISSUE TITLE
[BUG][Ruby Client] Plural rule is incorrect when message fell back to source

### ISSUE THREAD

**Issue by jessiejuachon** [vmware/singleton#1602] opened 2022-03-15 22:10 UTC
**Describe the bug**
When a key is not present in a translation bundle, or when the whole translation bundle is not yet available, source message/s is/are used. When this happens, the plural rule that is used is that of the original target locale instead of the source locale. The source locale plural rule must be used in such cases.

**To Reproduce**
Case 1
1. Use the ruby client library in a sample app.
2. Call getString_p on a bundle key that is not present in the target bundle (e.g. zh-Hant), but present in the source bundle.
3. Error: Notice that the plural rule used is that for en locale instead of zh-Hant.
Case 2
1. Use the ruby client library in a sample app.
2. Call getString_p on a target bundle (e.g. zh-Hant) that is not available, but source bundle is available.
3. Error: Notice that the plural rule used is that for en locale instead of zh-Hant.

**Expected behavior**
Plural rule to use must be that of the source locale.

**Comment by lyiyu66** [comment] 2022-05-18 15:18
Checked with build 0.7.0.36 with commit 09f7be8d62b86f6ae5c891a3c7d7e175059fa313, the issue is fixed with below case verification:
There is no messages_da.json in bundle, requesting locale "da" and count is "1.6" that belongs one category in da plural rule. The result returns en translation and uses other category since 1.6 is in other category in en plural rule.

**Closed by lyiyu66** 2022-05-18 15:18 UTC
Labels: kind/bug, priority/high, area/ruby-client
