### ISSUE TITLE
[service][REQUIREMENT] add # in key validate

### ISSUE THREAD

**Issue by tigershi** [vmware/singleton#1589] opened 2022-03-11 03:04 UTC
For Singleton Query Translation API: /i18n/api/v2/translation/products/{productName}/versions/{version}/locales/{locale}/components/{component}/keys/{key}

Generally the key only allows "letters, numbers, dot, underline, dashline (case-sensitive)" as the best practice to products. But according to internal feature design of Angular Client. The service API should add '#' support in key validation when query translation with single key.

Expected Result:
Allow keys with "#" inside when query translations with single key.

Actual Result:
Don't allow keys with "#" inside when query translations with single key.add the # in single key validate

**Comment by lyiyu66** [comment] 2022-03-15 02:07
The issue is fixed with commit 653b579d60fd4592493784e7c3f023d6b8372d6b

**Closed** 2022-03-15 02:10 UTC
Labels: area/java-service, kind/feature, priority/high
