### ISSUE TITLE
[BUG] [Java Service] \ in standard ascii but collect source failed when key contain "\" in POST&GET api both in V1&V2

### ISSUE THREAD

**Issue by JiLiang888** [vmware/singleton#1812] opened 2022-07-28 09:32 UTC
**Describe the bug**
\ in standard ascii but collect source failed when key contain "\" in POST api both in V1&V2

**To Reproduce**
1.use post api 
http://localhost:8091/i18n/api/v2/translation/products/test/versions/1.1.0/locales/en-US/components/0728post/keys/%23%2412%3Caa11%3E%3D%27%27%40%3B%5BAWE%7D~xyT%5E.%22df1%27-%3F%2B23-a%2A9%26%25%23%21%2C%2Fand?collectSource=true

![image](https://user-images.githubusercontent.com/82644009/181483378-23b4ee29-37ec-4bbd-b08b-9254a1fc8f66.png)

![image](https://user-images.githubusercontent.com/82644009/181483314-959b3dcb-32b4-45db-864d-499e14160fcf.png)

2. request key = \  or  double \

2. response error ,can see picture

**Expected behavior**
request key = \  or  double \

the key also can be collected .details can see below picture :
![image](https://user-images.githubusercontent.com/82644009/182283190-2e6b9b23-a48b-4ad2-88e2-6011d5c5bddb.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/82644009/181472879-cf22e6df-c4de-46d1-a095-2a7215d94b0b.png)

commit 93ffa26a7c0616ff7fee3eb25318342d1dc8975b

**Comment by lyiyu66** [comment] 2022-08-02 00:36
Same issue in V1 GET key-based APIs: Failed to collect or get the translation of key name with "\".
![image](https://user-images.githubusercontent.com/51813046/182267335-a81d1c13-4da5-4efc-8d8f-de9bf7eb1d33.png)

**Comment by lyiyu66** [comment] 2022-08-03 05:37
The issue is reproducible on l10n APIs:
V1:
GET /l10n/api/v1/source/products/{productName}/components/{component}/keys/{key}
V2:
POST /i18n​/l10n​/api​/v2​/translation​/products​/{productName}​/versions​/{version}​/locales​/{locale}​/components​/{component}​/keys​/{key}

**Comment by tigershi** [comment] 2022-08-19 02:04
this is swaggerui3's bug, it doesn't do the url encode, we need to wait the swaggers' upgrade.  Please use Postman do testing, it will be work successfully.

**Comment by lyiyu66** [comment] 2022-08-25 01:07
Tried with Postman, it still get same response.

**Comment by JiLiang888** [comment] 2022-08-26 09:37
test failed in 0826
![image](https://user-images.githubusercontent.com/82644009/186875617-a7794eae-6ea9-40eb-ad01-88046420ca21.png)

**Comment by lyiyu66** [comment] 2022-09-06 02:09
The issue is fixed with commit 5ff0dfac9f918c4b230a25a209c3c1d0c34bb6ae, the regression bug is tracked with new bug https://github.com/vmware/singleton/issues/1871

**Closed by lyiyu66** 2022-09-06 02:09 UTC
Labels: kind/bug, area/java-service, priority/medium
