### ISSUE TITLE
[BUG] [Service] Failed to generate build on Windows due to UT failed

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#1841] opened 2022-08-04 02:21 UTC
**Describe the bug**
UT failed when compile build with latest code.

**To Reproduce**
1. Pull latest code from master branch
2. run `gradlew build`
3. See error
`> Task :vip-manager-l10n:test FAILED`
```
com.vmware.l10n.source.service.TestSyncGrmSourceService > test001sendSourceToGRM
    java.lang.IllegalArgumentException at TestSyncGrmSourceService.java:93

com.vmware.l10n.utils.TestDiskQueueUtils > test002moveFile2I18nPath 
    java.lang.IllegalArgumentException at TestDiskQueueUtils.java:72

com.vmware.l10n.utils.TestDiskQueueUtils > test002moveFile2I18nPath 
    java.lang.IllegalArgumentException at TestDiskQueueUtils.java:72
```

**Expected behavior**
Build generated sucessfully without error.

**Comment by lyiyu66** [comment] 2022-08-15 06:44
The issue is fixed with commit d0ad488f2954faa46c6c5ea62e57ff1661f9a94c

**Closed by lyiyu66** 2022-08-15 06:44 UTC
Labels: kind/bug, area/java-service, priority/high
