### ISSUE TITLE
[BUG] [Java service][v1]Return to EN translation when no assigned locale in product API.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#1080] opened 2021-04-16 01:38 UTC
**Describe the bug**
build with commit: 30d4f9326a08cf696816bf2980b5bbe18c5832d5
Return to EN translation when no assigned locale in product API.

**To Reproduce**
1. Go to product API: /i18n/api/v1/translation
http://localhost:4022/i18n/api/v1/translation?productName=VPE&pseudo=false&version=1.0.0
2. See response:
```
{
  "response": {
    "code": 200,
    "message": "OK",
    "serverTime": ""
  },
  "signature": "",
  "data": {
    "productName": "VPE",
    "version": "1.0.0",
    "dataOrigin": "",
    "pseudo": false,
    "machineTranslation": false,
    "locales": [
      "en"
    ],
    "components": [
      "sunglow",
      "users"
    ],
    "bundles": [
      {
        "component": "sunglow",
        "messages": {
          "one.arg": "test one argument {0}",
          "plural.files": "{files, plural,one {category one : There is one file on {place}.}other {category other : There are # files on {place}.}}",
          "pagination": "{0} - {1} of {2} customers",
          "message": "Message-en"
        },
        "locale": "en"
      },
      {
        "component": "users",
        "messages": {
          "Singleton.description": "{0} is common lib developed by Singleton team.",
          "plural.files": "{0, plural,one {There is a file on \"{1}\".}other {There are # files on \"{1}\".}}",
          "plural.reserved.character": "{0, plural,one {This is sharp '#'.}other {There are # sharp '#'.}}"
        },
        "locale": "en"
      }
    ],
    "url": "",
    "id": 0
  }
}
```

**Expected behavior**
The translation of all supported locales and components should be shown.

**Comment by linr211** [comment] 2021-05-18 09:23
The behavior is by V1 design, not a bug. It's published and we are not continued to maintain this version.

**Comment by linr211** [comment] 2021-05-18 09:24
close it since it's by design.

**Closed** 2021-05-18 09:24 UTC
Labels: area/java-service, kind/bug, priority/medium
