### ISSUE TITLE
[BUG] [Java Service]Response code is 207 if request dup keys in Get mult-keys' translation api

### ISSUE THREAD

**Issue by JiLiang888** [vmware/singleton#2702] opened 2023-09-25 06:40 UTC
**Describe the bug**
[BUG] [Java Service]Response code is 207 if request dup keys in Get mult-keys' translation api

**To Reproduce**
1. Go to '[/i18n/api/v2/translation/products/{productName}/versions/{version}/locales/{locale}/components/{component}/keys]'
2. Request parameters as
<img width="1185" alt="image" src="https://github.com/vmware/singleton/assets/82644009/ceb97954-94b3-4953-a7ad-b4da2afebc08">

See response
response code =207 ;
<img width="1121" alt="image" src="https://github.com/vmware/singleton/assets/82644009/f7f50de6-b9f2-48bd-ac7b-f56a3a7b9010">

**Expected behavior**
response code =200;
response data should remove duplicate data

build.number.buildnumber=30dcfe321eeac05e989e9375563ba76465b4b62f

**Comment by JiLiang888** [comment] 2023-10-17 02:03
response code = 207 ;
build.number.buildnumber=f25e9d564eb33598f596db4bd62a2ef6d47724cf

**Comment by lyiyu66** [comment] 2023-10-26 02:21
The issue is fixed with commit 4be711789a4999cb03e7fdfb1f9fd16aa409a963
![image](https://github.com/vmware/singleton/assets/51813046/ac125419-ca4d-4107-ba67-a4faea02fc89)

**Closed** 2023-10-26 03:12 UTC
Labels: area/java-service, priority/medium
