### ISSUE TITLE
[BUG] [Service] Failed to unzip translation bundles when start Singleton Service

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#1867] opened 2022-08-31 10:23 UTC
**Describe the bug**
Translation bundle files failed to unzip when start Singleton Service Build

**To Reproduce**
1. Compile build with latest commit code
2. Start Singleton Service build
Error message:
```
2022-08-31 15:44:30,089 [VIP] [i18nManager] [INFO] [main]  com.vmware.vip.common.utils.UnzipTranslationUtils.unzipTransl
ationToLocal(UnzipTranslationUtils.java:111) - ***********************Begin Extract Bundle files************************
****
2022-08-31 15:44:30,115 [VIP] [i18nManager] [WARN] [main]  com.vmware.vip.messages.data.bundle.InitBundleListener.onAppl
icationEvent(InitBundleListener.java:44) - init bundle exception or no bundle file need to unzip
java.io.IOException: Bad zip entry
        at com.vmware.vip.common.l10n.source.util.FileUtil.unzipFiles(FileUtil.java:76) ~[vip-common-0.1.0.jar!/:?]
        at com.vmware.vip.common.utils.UnzipTranslationUtils.unzipTranslationToLocal(UnzipTranslationUtils.java:112) ~[v
ip-common-0.1.0.jar!/:?]
        at com.vmware.vip.messages.data.bundle.InitBundleListener.onApplicationEvent(InitBundleListener.java:41) ~[md-da
ta-api-bundleimpl-0.1.0.jar!/:0.1.0]
        at com.vmware.vip.messages.data.bundle.InitBundleListener.onApplicationEvent(InitBundleListener.java:19) ~[md-da
ta-api-bundleimpl-0.1.0.jar!/:0.1.0]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMu
lticaster.java:176) ~[spring-context-5.3.21.jar!/:5.3.21]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMult
icaster.java:169) ~[spring-context-5.3.21.jar!/:5.3.21]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMult
icaster.java:143) ~[spring-context-5.3.21.jar!/:5.3.21]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:4
21) ~[spring-context-5.3.21.jar!/:5.3.21]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:3
78) ~[spring-context-5.3.21.jar!/:5.3.21]
        at org.springframework.boot.context.event.EventPublishingRunListener.ready(EventPublishingRunListener.java:114)
~[spring-boot-2.7.1.jar!/:2.7.1]
        at org.springframework.boot.SpringApplicationRunListeners.lambda$ready$6(SpringApplicationRunListeners.java:82)
~[spring-boot-2.7.1.jar!/:2.7.1]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_161]
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120
) ~[spring-boot-2.7.1.jar!/:2.7.1]
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114
) ~[spring-boot-2.7.1.jar!/:2.7.1]
        at org.springframework.boot.SpringApplicationRunListeners.ready(SpringApplicationRunListeners.java:82) ~[spring-
boot-2.7.1.jar!/:2.7.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:323) ~[spring-boot-2.7.1.jar!/:2.7.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.1.jar!/:2.7.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.1.jar!/:2.7.1]
        at com.vmware.vip.BootApplication.main(BootApplication.java:43) ~[classes!/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[singleton-manager-i18n-0.6.7
.jar:?]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[singleton-manager-i18n-0.6.7.jar:?]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[singleton-manager-i18n-0.6.7.jar:?]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[singleton-manager-i18n-0.6.7.jar:?]
2022-08-31 15:44:30,148 [VIP] [i18nManager] [INFO] [main]  com.vmware.vip.messages.data.bundle.InitBundleListener.onAppl
icationEvent(InitBundleListener.java:49) - init the bundles end
```

**Expected behavior**
The translation bundles should be extracted successfully.

**Comment by lyiyu66** [comment] 2022-09-06 02:32
The issue is fixed with commit 5ff0dfac9f918c4b230a25a209c3c1d0c34bb6ae

**Closed by lyiyu66** 2022-09-06 02:32 UTC
Labels: kind/bug, area/java-service, priority/high
