### ISSUE TITLE
[Java client][BUG] Numerous error logs is seen from LocalMessagesOpt

### ISSUE THREAD

**Issue by jessiejuachon** [vmware/singleton#1025] opened 2021-02-23 16:36 UTC
**Describe the bug**
The log below is seen by Atlas team 20,000+ times in 24 hours.

**To Reproduce**
2021-02-18 22:05:07.415 GMT core-inventory-6cc9f5c9fc-dgx25 [priority='ERROR' thread='http-nio-8080-exec-9' user='rkayan@vmware.com' org='061f5167-fe81-4310-b62d-df24ff21db7d' trace='4e88fc6c-9969-9634-b9bb-1966f67b1e09'] com.vmware.vipclient.i18n.messages.api.opt.local.LocalMessagesOpt@? - Failed to get offline messages for product: VMC 2.0.0, component: core-inventory, locale: source, exception: Failed to get resource bundle for locale: source 

**Additional context**
The log above was reported by Atlas team.
This bug is related to issue #863 , PR #864.

**Comment by huihuiw01** [comment] 2021-03-29 09:41
Considering the user cases without messages_source.json from VCF, Dell Jessiely provided, we shouldn’t log error for ‘source’ locale;
but as I mentioned in email, without messages_source.json there will be no comparison feature for offline mode. In another word, if comparison feature is required,  messages_source.json is required. Then I shouldn’t change the log level.

According to Jessiely's email, she had a discussion about comparison feature with Demin, and will send out the summary. So I will wait for her summary of comparison feature and hold on the fix.

**Comment by lyiyu66** [comment] 2021-05-31 02:48
The issue is fixed with commit 8ffcfaa069cc5e2992ebbeb4ae99fe5eb7df73c4. The message is changed from error to debug.
![image](https://user-images.githubusercontent.com/51813046/120132869-abe91d00-c1fd-11eb-8c59-06ee62a309ce.png)

**Closed by lyiyu66** 2021-05-31 02:48 UTC
Labels: area/java-client, kind/bug
