### ISSUE TITLE
[BUG] [Ruby Client] Can't replace placeholder "{0}, {1}" by getString_f()

### ISSUE THREAD

**Issue by dleng-vmware** [vmware/singleton#1284] opened 2021-08-27 01:06 UTC
**Describe the bug**
Can't replace placeholder "{0}, {1}" by getString_f()
**GetString_f() should replace placeholder "{0}" rather than "%s",because the placeholders in the l10n bundle are {string}**

**To Reproduce**
1. Set the value of key "key1" be "{0} {1} TEST VALUE"
2.  SgtnClient::Source.loadBundles("default")
     result = SgtnClient::Translation.getString_f("JAVA", "key1",["a1","a2"], "de")
**the result return "{0} {1} TEST VALUE"**

**Expected behavior**
Result should be "a1 a2 TEST VALUE"

**Comment by linr211** [comment] 2021-08-30 11:30
The correct usage is '%{number}$s', e.g.‘%2$s, welcome login %1$s’, so it's not a bug.

**Comment by Xiaochao8** [comment] 2021-09-10 01:12
Please verify it in Ruby way rather than ICU way.

**Comment by lyiyu66** [comment] 2021-09-10 03:07
Thanks for comment. In this case, the bug is not a bug. Hence closing.

**Closed by lyiyu66** 2021-09-10 03:07 UTC
Labels: kind/bug, triage/invalid, priority/high, area/ruby-client
