### ISSUE TITLE
[REQUIREMENT][Service] Support to generate javadoc & source in gradlew

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#1701] opened 2022-05-18 09:39 UTC
In Singleton Service build, we suggest to use gradlew to generate build, but when publish build to maven, it also needs source and javadoc, to make it consistent, please also add to generate javadoc and source in gradlew.

**Comment by lyiyu66** [comment] 2022-08-04 01:08
The issue is fixed with commit 9be403f621a76b4d1349ce4e81ce58f585b7cc8c.
![image](https://user-images.githubusercontent.com/51813046/182741384-761a2494-b679-4bc4-a56d-449b17f55d63.png)

**Closed by lyiyu66** 2022-08-04 01:08 UTC
Labels: kind/enhancement, area/java-service, priority/medium
