### ISSUE TITLE
[BUG] The offlineResourceBaseURL inside a shared lib is not being read if main app is is run from IDE and not built as an executable jar

### ISSUE THREAD

**Issue by jessiejuachon** [vmware/singleton#868] opened 2020-11-11 06:02 UTC
**Describe the bug**
The offlineResourceBaseURL inside the shared lib is not being read because it only considers the first uri match even if there can be multiple uris from dependency jars.
As a result, one of the sample apps is failing in IDE only, but not when run as a fat jar.

**To Reproduce**
1. git clone
2. cd singleton 
3. git checkout g11n-java-client
4. cd sample-client-app/sample-app-with-shared-lib
5. build using IDE
6. run Main class from IDE
7. Notice the exception

**Expected behavior**
No exception should be thrown, just like if you do the following:
5. gradle build
6. java -jar ./build/libs/sample-with-shared-lib-1.0.jar

**Comment by jessiejuachon** [comment] 2020-11-17 05:30
The same behavior happens when application packaging ha nested jars (e.g. in Spring boot apps) so changed the priority of this from medium to high

**Comment by lyiyu66** [comment] 2020-12-15 02:08
The issue is same as issue ##882 and it has been fixed with commit 3678872.

**Closed by lyiyu66** 2020-12-15 02:08 UTC
Labels: area/java-client, kind/bug, priority/high
