### ISSUE TITLE
[BUG] [Ruby Client]Fail to start app when an empty folder under source path

### ISSUE THREAD

**Issue by Xiaochao8** [vmware/singleton#1274] opened 2021-08-20 02:52 UTC

**Comment by linr211** [comment] 2021-08-20 12:28
This is by design, meaning for an component, it's required to have default file under it, otherwise it will failed to start app.

**Comment by Xiaochao8** [comment] 2021-11-05 02:03
It doesn't make sense to stop the application just because an empty folder.

**Comment by lyiyu66** [comment] 2022-05-18 14:29
Checked with build 0.7.0.36 with commit 09f7be8d62b86f6ae5c891a3c7d7e175059fa313, the issue is fixed in below scenario: no source file in component2

source directory:
source
 -component1
   -default.yml
 -component2
 -component3
   -default.yml

**Closed** 2022-05-18 14:29 UTC
Labels: kind/bug, priority/low, area/ruby-client
