### ISSUE TITLE
[BUG] [Java Client] org.apache.jasper.JasperException: Unable to find taglib [vip] for URI: [/vip].

### ISSUE THREAD

**Issue by huihuiw01** [vmware/singleton#2785] opened 2023-10-24 03:17 UTC
**Describe the bug**
When use our customized tag <vip> in jsp page, below exception is reported:
org.apache.jasper.JasperException: Unable to find taglib [vip] for URI: [/vip].

**To Reproduce**
1. create an web application
2. add java client library dependency
3. add a jsp page
4. add the tag lib import in jsp page: <%@ taglib prefix="vip" uri="/vip" %>
5. use the tag in jsp page, for example: <vip:message key="admin.page.certificates" />
6. start the web application and access the jsp page

**Expected behavior**
No exception is reported and UI page can show correctly.

**Screenshots**

**Desktop (please complete the following information):**
 

**Additional context**

**Comment by lyiyu66** [comment] 2023-11-01 10:59
The issue is fixed with commit f1f6a909a7452d8652148ce242a51b86cde0d25f, no exception is occurred.
![image](https://github.com/vmware/singleton/assets/51813046/1f36f23b-1056-4d57-8954-36fb3d9da46b)

**Closed by lyiyu66** 2023-11-01 10:59 UTC
Labels: kind/bug, area/java-client, priority/medium
